#!/usr/bin/python2.7
"""Read in a .gmail-json file (generated by download_gmail_folder.py) and print
some statistics abouts it."""

from collections import defaultdict
import sys
import re
import json
import email.parser
import datetime
import dateutil.parser

import utils
import gmail_utils

assert len(sys.argv) == 3
command, input_json = sys.argv[1:]
assert command in ['dates', 'from', 'subjects']

data = json.load(file(input_json))


for idx, msg_pair in enumerate(data):
  msg = gmail_utils.ParseMessagePair(msg_pair)
  if not msg: continue

  if command == 'dates':
    print msg['date'].strftime('%Y-%m-%d') + ' %s' % msg['date']
  elif command == 'from':
    print msg['from']
